# Generated by Django 4.1.3 on 2022-11-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='notPost',
        ),
    ]
